name: ci-push

on: push

jobs:
  cmake-build:
    uses: ./reusable-cmake.yml
    with:
      cmake-options: -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR="ZIP"
      enable-build: true
      enable-tests: true
      enable-package: true
