name: ci-push

on: push

jobs:
  cmake-build:
    uses: ./.github/workflows/reusable-cmake.yml
    with:
      cmake-options: -DCMAKE_BUILD_TYPE=Release
      enable-build: true
      enable-test: true
      enable-package: false

  cmake-packaging:
    uses: ./.github/workflows/reusable-cmake.yml
    with:
      cmake-options: -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR="ZIP"
      enable-build: true
      enable-test: false
      enable-package: true
      artifact-name: package

  package-test:
    needs: cmake-packaging
    uses: ./.github/workflows/reusable-package-test.yml
    with:
      artifact-name: package