name: dispatch-docker-build

on: workflow_dispatch

permissions:
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
      # - name: Build container
      #   run: docker build --push -t ghcr.io/27cobalter/push-test/alpine:latest docker/manual/
      - name: Buildx
        working-directory: docker/bake
        run: docker buildx bake --push --file bake.hcl
