name: dispatch-docker-run

on: workflow_dispatch

permissions:
  packages: write

jobs:
  run-docker-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "alpine-base", "ubuntu-base" ]
    container:
      image: ghcr.io/27cobalter/actions-test/${{ matrix.image }}:latest
    steps:
      - name: info
        run: |
          pwd
          ls /etc/
          ls /
      - name: Run tesh.sh
        run: sh /test.sh
