name: dispatch-docker-bake
on: workflow_dispatch

permissions:
  packages: write

jobs:
  docker-bake:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ github.token}}
      - name: Bake
        uses: docker/bake-action@v5
        with:
          files: bake.hcl
          workdir: docker/bake
          targets: default
          provenance: false
          push: true