name: reusable-package-test

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        default: package

jobs:
  package-test:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
          path: ./artifact
      - name: find
        run: find . -type f
      - name: install
        run: sudo dpkg -i $(find artifact -name "*.deb")
      - name: run
        run: /opt/actions-test/bin/main