name: reusable-cmake

on:
  workflow_call:
    inputs:
      source-dir:
        type: string
        default: "./"
      build-dir:
        type: string
        default: "build"
      cmake-options:
        type: string
      enable-build:
        type: boolean
        default: false
      enable-test:
        type: boolean
        default: false
      enable-package:
        type: boolean
        default: false

jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -B ${{inputs.build-dir}} -S ${{inputs.source-dir}} ${{inputs.cmake-options}}
      - name: build
        if: ${{inputs.enable-build}}
        run: cmake --build ${{inputs.build-dir}}
      - name: test
        if: ${{inputs.enable-test}}
        run: cmake --build ${{inputs.build-dir}} --target test
      - name: package
        if: ${{inputs.enable-package}}
        run: cmake --build ${{inputs.build-dir}} --target package
      - name: upload
        if: ${{inputs.enable-package}}
        uses: actions/upload-artifact@v4
        with:
          name: zip-package
          path: |
            ${{inputs.build-dir}}/package/actions-test-*
          if-no-files-found: error

